//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Math.Tools.TrackReaders.Gpx {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/1/1", IsNullable=false)]
    public partial class gpx {
        
        private gpxMetadata metadataField;
        
        private gpxRte rteField;
        
        private gpxTrk trkField;
        
        private decimal versionField;
        
        private string creatorField;
        
        /// <remarks/>
        public gpxMetadata metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        public gpxRte rte {
            get {
                return this.rteField;
            }
            set {
                this.rteField = value;
            }
        }
        
        /// <remarks/>
        public gpxTrk trk {
            get {
                return this.trkField;
            }
            set {
                this.trkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class gpxMetadata {
        
        private gpxMetadataAuthor authorField;
        
        private gpxMetadataLink linkField;
        
        private System.DateTime timeField;
        
        /// <remarks/>
        public gpxMetadataAuthor author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        public gpxMetadataLink link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class gpxMetadataAuthor {
        
        private string nameField;
        
        private gpxMetadataAuthorEmail emailField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public gpxMetadataAuthorEmail email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class gpxMetadataAuthorEmail {
        
        private string idField;
        
        private string domainField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.garmin.com/xmlschemas/TrackPointExtension/v1")]
    public partial class Extensions_t {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.garmin.com/xmlschemas/TrackPointExtension/v1")]
    [System.Xml.Serialization.XmlRootAttribute("TrackPointExtension", Namespace="http://www.garmin.com/xmlschemas/TrackPointExtension/v1", IsNullable=false)]
    public partial class TrackPointExtension_t {
        
        private double atempField;
        
        private bool atempFieldSpecified;
        
        private double wtempField;
        
        private bool wtempFieldSpecified;
        
        private double depthField;
        
        private bool depthFieldSpecified;
        
        private byte hrField;
        
        private bool hrFieldSpecified;
        
        private byte cadField;
        
        private bool cadFieldSpecified;
        
        private Extensions_t extensionsField;
        
        /// <remarks/>
        public double atemp {
            get {
                return this.atempField;
            }
            set {
                this.atempField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool atempSpecified {
            get {
                return this.atempFieldSpecified;
            }
            set {
                this.atempFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double wtemp {
            get {
                return this.wtempField;
            }
            set {
                this.wtempField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool wtempSpecified {
            get {
                return this.wtempFieldSpecified;
            }
            set {
                this.wtempFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double depth {
            get {
                return this.depthField;
            }
            set {
                this.depthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool depthSpecified {
            get {
                return this.depthFieldSpecified;
            }
            set {
                this.depthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public byte hr {
            get {
                return this.hrField;
            }
            set {
                this.hrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hrSpecified {
            get {
                return this.hrFieldSpecified;
            }
            set {
                this.hrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public byte cad {
            get {
                return this.cadField;
            }
            set {
                this.cadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cadSpecified {
            get {
                return this.cadFieldSpecified;
            }
            set {
                this.cadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Extensions_t Extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class gpxMetadataLink {
        
        private string textField;
        
        private string hrefField;
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class gpxRte {
        
        private string nameField;
        
        private string cmtField;
        
        private string descField;
        
        private string srcField;
        
        private gpxRteLink linkField;
        
        private string numberField;
        
        private string typeField;
        
        private gpxRteRtept[] rteptField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string cmt {
            get {
                return this.cmtField;
            }
            set {
                this.cmtField = value;
            }
        }
        
        /// <remarks/>
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
        
        /// <remarks/>
        public gpxRteLink link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rtept")]
        public gpxRteRtept[] rtept {
            get {
                return this.rteptField;
            }
            set {
                this.rteptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class gpxRteLink {
        
        private string textField;
        
        private string hrefField;
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class gpxRteRtept {
        
        private decimal eleField;
        
        private bool eleFieldSpecified;
        
        private System.DateTime timeField;
        
        private bool timeFieldSpecified;
        
        private decimal magvarField;
        
        private bool magvarFieldSpecified;
        
        private decimal geoidheightField;
        
        private bool geoidheightFieldSpecified;
        
        private string nameField;
        
        private string cmtField;
        
        private string descField;
        
        private string srcField;
        
        private gpxRteRteptLink linkField;
        
        private string symField;
        
        private string typeField;
        
        private gpxRteRteptFix fixField;
        
        private bool fixFieldSpecified;
        
        private string satField;
        
        private decimal hdopField;
        
        private bool hdopFieldSpecified;
        
        private decimal vdopField;
        
        private bool vdopFieldSpecified;
        
        private decimal pdopField;
        
        private bool pdopFieldSpecified;
        
        private decimal ageofdgpsdataField;
        
        private bool ageofdgpsdataFieldSpecified;
        
        private string dgpsidField;
        
        private decimal latField;
        
        private decimal lonField;
        
        /// <remarks/>
        public decimal ele {
            get {
                return this.eleField;
            }
            set {
                this.eleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eleSpecified {
            get {
                return this.eleFieldSpecified;
            }
            set {
                this.eleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified {
            get {
                return this.timeFieldSpecified;
            }
            set {
                this.timeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal magvar {
            get {
                return this.magvarField;
            }
            set {
                this.magvarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool magvarSpecified {
            get {
                return this.magvarFieldSpecified;
            }
            set {
                this.magvarFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal geoidheight {
            get {
                return this.geoidheightField;
            }
            set {
                this.geoidheightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool geoidheightSpecified {
            get {
                return this.geoidheightFieldSpecified;
            }
            set {
                this.geoidheightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string cmt {
            get {
                return this.cmtField;
            }
            set {
                this.cmtField = value;
            }
        }
        
        /// <remarks/>
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
        
        /// <remarks/>
        public gpxRteRteptLink link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public string sym {
            get {
                return this.symField;
            }
            set {
                this.symField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public gpxRteRteptFix fix {
            get {
                return this.fixField;
            }
            set {
                this.fixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fixSpecified {
            get {
                return this.fixFieldSpecified;
            }
            set {
                this.fixFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string sat {
            get {
                return this.satField;
            }
            set {
                this.satField = value;
            }
        }
        
        /// <remarks/>
        public decimal hdop {
            get {
                return this.hdopField;
            }
            set {
                this.hdopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hdopSpecified {
            get {
                return this.hdopFieldSpecified;
            }
            set {
                this.hdopFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal vdop {
            get {
                return this.vdopField;
            }
            set {
                this.vdopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdopSpecified {
            get {
                return this.vdopFieldSpecified;
            }
            set {
                this.vdopFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal pdop {
            get {
                return this.pdopField;
            }
            set {
                this.pdopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pdopSpecified {
            get {
                return this.pdopFieldSpecified;
            }
            set {
                this.pdopFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal ageofdgpsdata {
            get {
                return this.ageofdgpsdataField;
            }
            set {
                this.ageofdgpsdataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ageofdgpsdataSpecified {
            get {
                return this.ageofdgpsdataFieldSpecified;
            }
            set {
                this.ageofdgpsdataFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string dgpsid {
            get {
                return this.dgpsidField;
            }
            set {
                this.dgpsidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lon {
            get {
                return this.lonField;
            }
            set {
                this.lonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class gpxRteRteptLink {
        
        private string textField;
        
        private string hrefField;
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/1")]
    public enum gpxRteRteptFix {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2d")]
        Item2d,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3d")]
        Item3d,
        
        /// <remarks/>
        dgps,
        
        /// <remarks/>
        pps,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class gpxTrk {
        
        private string srcField;
        
        private gpxTrkLink linkField;
        
        private string typeField;
        
        private gpxTrkTrkpt[] trksegField;
        
        /// <remarks/>
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
        
        /// <remarks/>
        public gpxTrkLink link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("trkpt", IsNullable=false)]
        public gpxTrkTrkpt[] trkseg {
            get {
                return this.trksegField;
            }
            set {
                this.trksegField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class gpxTrkLink {
        
        private string textField;
        
        private string hrefField;
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class gpxTrkTrkpt {
        
        private decimal eleField;
        
        private System.DateTime timeField;
        
        private gpxTrkTrkptExtensions extensionsField;
        
        private decimal latField;
        
        private decimal lonField;
        
        /// <remarks/>
        public decimal ele {
            get {
                return this.eleField;
            }
            set {
                this.eleField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        public gpxTrkTrkptExtensions extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lon {
            get {
                return this.lonField;
            }
            set {
                this.lonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class gpxTrkTrkptExtensions {
        
        private TrackPointExtension_t trackPointExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.garmin.com/xmlschemas/TrackPointExtension/v1")]
        public TrackPointExtension_t TrackPointExtension {
            get {
                return this.trackPointExtensionField;
            }
            set {
                this.trackPointExtensionField = value;
            }
        }
    }
}
