//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Math.Tools.TrackReaders.Kml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class Icon {
        
        private string hrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class IconStyle {
        
        private Icon iconField;
        
        /// <remarks/>
        public Icon Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class LineStyle {
        
        private byte[] colorField;
        
        private double widthField;
        
        private bool widthFieldSpecified;
        
        public LineStyle() {
            this.widthField = 1D;
        }
        
        /// <remarks/>
        // CODEGEN Warning: 'default' attribute on items of type 'hexBinary' is not supported in this version of the .Net Framework.  Ignoring default='ffffffff' attribute.
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public double width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool widthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class PolyStyle {
        
        private byte[] colorField;
        
        /// <remarks/>
        // CODEGEN Warning: 'default' attribute on items of type 'hexBinary' is not supported in this version of the .Net Framework.  Ignoring default='ffffffff' attribute.
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class BalloonStyle {
        
        private string textField;
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class Point {
        
        private bool extrudeField;
        
        private bool extrudeFieldSpecified;
        
        private altitudeModeEnumType altitudeModeField;
        
        private bool altitudeModeFieldSpecified;
        
        private string coordinatesField;
        
        public Point() {
            this.extrudeField = false;
            this.altitudeModeField = altitudeModeEnumType.clampToGround;
        }
        
        /// <remarks/>
        public bool extrude {
            get {
                return this.extrudeField;
            }
            set {
                this.extrudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool extrudeSpecified {
            get {
                return this.extrudeFieldSpecified;
            }
            set {
                this.extrudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public altitudeModeEnumType altitudeMode {
            get {
                return this.altitudeModeField;
            }
            set {
                this.altitudeModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool altitudeModeSpecified {
            get {
                return this.altitudeModeFieldSpecified;
            }
            set {
                this.altitudeModeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute("altitudeMode", Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public enum altitudeModeEnumType {
        
        /// <remarks/>
        clampToGround,
        
        /// <remarks/>
        relativeToGround,
        
        /// <remarks/>
        absolute,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class LookAt {
        
        private double longitudeField;
        
        private double latitudeField;
        
        private double altitudeField;
        
        private bool altitudeFieldSpecified;
        
        private double headingField;
        
        private double tiltField;
        
        private double rangeField;
        
        public LookAt() {
            this.longitudeField = 0D;
            this.latitudeField = 0D;
            this.altitudeField = 0D;
            this.headingField = 0D;
            this.tiltField = 0D;
            this.rangeField = 0D;
        }
        
        /// <remarks/>
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool altitudeSpecified {
            get {
                return this.altitudeFieldSpecified;
            }
            set {
                this.altitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
            }
        }
        
        /// <remarks/>
        public double tilt {
            get {
                return this.tiltField;
            }
            set {
                this.tiltField = value;
            }
        }
        
        /// <remarks/>
        public double range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class Placemark {
        
        private string nameField;
        
        private bool visibilityField;
        
        private bool visibilityFieldSpecified;
        
        private string descriptionField;
        
        private LookAt lookAtField;
        
        private string styleUrlField;
        
        private Point pointField;
        
        private LineString lineStringField;
        
        private Polygon polygonField;
        
        public Placemark() {
            this.visibilityField = true;
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool visibilitySpecified {
            get {
                return this.visibilityFieldSpecified;
            }
            set {
                this.visibilityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public LookAt LookAt {
            get {
                return this.lookAtField;
            }
            set {
                this.lookAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string styleUrl {
            get {
                return this.styleUrlField;
            }
            set {
                this.styleUrlField = value;
            }
        }
        
        /// <remarks/>
        public Point Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
        
        /// <remarks/>
        public LineString LineString {
            get {
                return this.lineStringField;
            }
            set {
                this.lineStringField = value;
            }
        }
        
        /// <remarks/>
        public Polygon Polygon {
            get {
                return this.polygonField;
            }
            set {
                this.polygonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class LineString {
        
        private bool extrudeField;
        
        private bool extrudeFieldSpecified;
        
        private bool tessellateField;
        
        private altitudeModeEnumType altitudeModeField;
        
        private bool altitudeModeFieldSpecified;
        
        private string coordinatesField;
        
        public LineString() {
            this.extrudeField = false;
            this.tessellateField = false;
            this.altitudeModeField = altitudeModeEnumType.clampToGround;
        }
        
        /// <remarks/>
        public bool extrude {
            get {
                return this.extrudeField;
            }
            set {
                this.extrudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool extrudeSpecified {
            get {
                return this.extrudeFieldSpecified;
            }
            set {
                this.extrudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool tessellate {
            get {
                return this.tessellateField;
            }
            set {
                this.tessellateField = value;
            }
        }
        
        /// <remarks/>
        public altitudeModeEnumType altitudeMode {
            get {
                return this.altitudeModeField;
            }
            set {
                this.altitudeModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool altitudeModeSpecified {
            get {
                return this.altitudeModeFieldSpecified;
            }
            set {
                this.altitudeModeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class Polygon {
        
        private bool extrudeField;
        
        private bool extrudeFieldSpecified;
        
        private bool tessellateField;
        
        private bool tessellateFieldSpecified;
        
        private altitudeModeEnumType altitudeModeField;
        
        private outerBoundaryIs outerBoundaryIsField;
        
        private innerBoundaryIs innerBoundaryIsField;
        
        public Polygon() {
            this.extrudeField = false;
            this.tessellateField = false;
            this.altitudeModeField = altitudeModeEnumType.clampToGround;
        }
        
        /// <remarks/>
        public bool extrude {
            get {
                return this.extrudeField;
            }
            set {
                this.extrudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool extrudeSpecified {
            get {
                return this.extrudeFieldSpecified;
            }
            set {
                this.extrudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool tessellate {
            get {
                return this.tessellateField;
            }
            set {
                this.tessellateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tessellateSpecified {
            get {
                return this.tessellateFieldSpecified;
            }
            set {
                this.tessellateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public altitudeModeEnumType altitudeMode {
            get {
                return this.altitudeModeField;
            }
            set {
                this.altitudeModeField = value;
            }
        }
        
        /// <remarks/>
        public outerBoundaryIs outerBoundaryIs {
            get {
                return this.outerBoundaryIsField;
            }
            set {
                this.outerBoundaryIsField = value;
            }
        }
        
        /// <remarks/>
        public innerBoundaryIs innerBoundaryIs {
            get {
                return this.innerBoundaryIsField;
            }
            set {
                this.innerBoundaryIsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class outerBoundaryIs {
        
        private LinearRing linearRingField;
        
        /// <remarks/>
        public LinearRing LinearRing {
            get {
                return this.linearRingField;
            }
            set {
                this.linearRingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class LinearRing {
        
        private string coordinatesField;
        
        /// <remarks/>
        public string coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class innerBoundaryIs {
        
        private LinearRing linearRingField;
        
        /// <remarks/>
        public LinearRing LinearRing {
            get {
                return this.linearRingField;
            }
            set {
                this.linearRingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class Pair {
        
        private styleStateEnumType keyField;
        
        private string styleUrlField;
        
        public Pair() {
            this.keyField = styleStateEnumType.normal;
        }
        
        /// <remarks/>
        public styleStateEnumType key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string styleUrl {
            get {
                return this.styleUrlField;
            }
            set {
                this.styleUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute("key", Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public enum styleStateEnumType {
        
        /// <remarks/>
        normal,
        
        /// <remarks/>
        highlight,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class Style {
        
        private IconStyle iconStyleField;
        
        private LineStyle lineStyleField;
        
        private PolyStyle polyStyleField;
        
        private BalloonStyle balloonStyleField;
        
        private string idField;
        
        /// <remarks/>
        public IconStyle IconStyle {
            get {
                return this.iconStyleField;
            }
            set {
                this.iconStyleField = value;
            }
        }
        
        /// <remarks/>
        public LineStyle LineStyle {
            get {
                return this.lineStyleField;
            }
            set {
                this.lineStyleField = value;
            }
        }
        
        /// <remarks/>
        public PolyStyle PolyStyle {
            get {
                return this.polyStyleField;
            }
            set {
                this.polyStyleField = value;
            }
        }
        
        /// <remarks/>
        public BalloonStyle BalloonStyle {
            get {
                return this.balloonStyleField;
            }
            set {
                this.balloonStyleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class StyleMap {
        
        private Pair[] pairField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Pair")]
        public Pair[] Pair {
            get {
                return this.pairField;
            }
            set {
                this.pairField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class Document {
        
        private string nameField;
        
        private bool visibilityField;
        
        private bool visibilityFieldSpecified;
        
        private bool openField;
        
        private bool openFieldSpecified;
        
        private string descriptionField;
        
        private LookAt lookAtField;
        
        private Style[] styleField;
        
        private StyleMap styleMapField;
        
        private Placemark placemarkField;
        
        private Folder[] folderField;
        
        public Document() {
            this.visibilityField = true;
            this.openField = false;
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool visibilitySpecified {
            get {
                return this.visibilityFieldSpecified;
            }
            set {
                this.visibilityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool open {
            get {
                return this.openField;
            }
            set {
                this.openField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool openSpecified {
            get {
                return this.openFieldSpecified;
            }
            set {
                this.openFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public LookAt LookAt {
            get {
                return this.lookAtField;
            }
            set {
                this.lookAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Style")]
        public Style[] Style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
        
        /// <remarks/>
        public StyleMap StyleMap {
            get {
                return this.styleMapField;
            }
            set {
                this.styleMapField = value;
            }
        }
        
        /// <remarks/>
        public Placemark Placemark {
            get {
                return this.placemarkField;
            }
            set {
                this.placemarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folder")]
        public Folder[] Folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class Folder {
        
        private string nameField;
        
        private bool visibilityField;
        
        private bool visibilityFieldSpecified;
        
        private string descriptionField;
        
        private LookAt lookAtField;
        
        private string styleUrlField;
        
        private Document documentField;
        
        private Placemark[] placemarkField;
        
        private GroundOverlay groundOverlayField;
        
        private ScreenOverlay[] screenOverlayField;
        
        private Folder[] folder1Field;
        
        public Folder() {
            this.visibilityField = true;
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool visibilitySpecified {
            get {
                return this.visibilityFieldSpecified;
            }
            set {
                this.visibilityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public LookAt LookAt {
            get {
                return this.lookAtField;
            }
            set {
                this.lookAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string styleUrl {
            get {
                return this.styleUrlField;
            }
            set {
                this.styleUrlField = value;
            }
        }
        
        /// <remarks/>
        public Document Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Placemark")]
        public Placemark[] Placemark {
            get {
                return this.placemarkField;
            }
            set {
                this.placemarkField = value;
            }
        }
        
        /// <remarks/>
        public GroundOverlay GroundOverlay {
            get {
                return this.groundOverlayField;
            }
            set {
                this.groundOverlayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScreenOverlay")]
        public ScreenOverlay[] ScreenOverlay {
            get {
                return this.screenOverlayField;
            }
            set {
                this.screenOverlayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folder")]
        public Folder[] Folder1 {
            get {
                return this.folder1Field;
            }
            set {
                this.folder1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class GroundOverlay {
        
        private string nameField;
        
        private bool visibilityField;
        
        private string descriptionField;
        
        private LookAt lookAtField;
        
        private Icon iconField;
        
        private LatLonBox latLonBoxField;
        
        public GroundOverlay() {
            this.visibilityField = true;
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public LookAt LookAt {
            get {
                return this.lookAtField;
            }
            set {
                this.lookAtField = value;
            }
        }
        
        /// <remarks/>
        public Icon Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
        
        /// <remarks/>
        public LatLonBox LatLonBox {
            get {
                return this.latLonBoxField;
            }
            set {
                this.latLonBoxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class LatLonBox {
        
        private double northField;
        
        private double southField;
        
        private double eastField;
        
        private double westField;
        
        private double rotationField;
        
        public LatLonBox() {
            this.northField = 180D;
            this.southField = -180D;
            this.eastField = 180D;
            this.westField = -180D;
            this.rotationField = 0D;
        }
        
        /// <remarks/>
        public double north {
            get {
                return this.northField;
            }
            set {
                this.northField = value;
            }
        }
        
        /// <remarks/>
        public double south {
            get {
                return this.southField;
            }
            set {
                this.southField = value;
            }
        }
        
        /// <remarks/>
        public double east {
            get {
                return this.eastField;
            }
            set {
                this.eastField = value;
            }
        }
        
        /// <remarks/>
        public double west {
            get {
                return this.westField;
            }
            set {
                this.westField = value;
            }
        }
        
        /// <remarks/>
        public double rotation {
            get {
                return this.rotationField;
            }
            set {
                this.rotationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class ScreenOverlay {
        
        private string nameField;
        
        private bool visibilityField;
        
        private string descriptionField;
        
        private Icon iconField;
        
        private vec2Type overlayXYField;
        
        private vec2Type screenXYField;
        
        private vec2Type rotationXYField;
        
        private vec2Type sizeField;
        
        public ScreenOverlay() {
            this.visibilityField = true;
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public Icon Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
        
        /// <remarks/>
        public vec2Type overlayXY {
            get {
                return this.overlayXYField;
            }
            set {
                this.overlayXYField = value;
            }
        }
        
        /// <remarks/>
        public vec2Type screenXY {
            get {
                return this.screenXYField;
            }
            set {
                this.screenXYField = value;
            }
        }
        
        /// <remarks/>
        public vec2Type rotationXY {
            get {
                return this.rotationXYField;
            }
            set {
                this.rotationXYField = value;
            }
        }
        
        /// <remarks/>
        public vec2Type size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute("hotSpot", Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class vec2Type {
        
        private double xField;
        
        private double yField;
        
        private unitsEnumType xunitsField;
        
        private unitsEnumType yunitsField;
        
        public vec2Type() {
            this.xField = 1D;
            this.yField = 1D;
            this.xunitsField = unitsEnumType.fraction;
            this.yunitsField = unitsEnumType.fraction;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(unitsEnumType.fraction)]
        public unitsEnumType xunits {
            get {
                return this.xunitsField;
            }
            set {
                this.xunitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(unitsEnumType.fraction)]
        public unitsEnumType yunits {
            get {
                return this.yunitsField;
            }
            set {
                this.yunitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/kml/2.2")]
    public enum unitsEnumType {
        
        /// <remarks/>
        fraction,
        
        /// <remarks/>
        pixels,
        
        /// <remarks/>
        insetPixels,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class kml {
        
        private Document documentField;
        
        /// <remarks/>
        public Document Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute("colorMode", Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public enum colorModeEnumType {
        
        /// <remarks/>
        normal,
        
        /// <remarks/>
        random,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute("displayMode", Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public enum displayModeEnumType {
        
        /// <remarks/>
        @default,
        
        /// <remarks/>
        hide,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute("gridOrigin", Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public enum gridOriginEnumType {
        
        /// <remarks/>
        lowerLeft,
        
        /// <remarks/>
        upperLeft,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute("listItemType", Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public enum listItemTypeEnumType {
        
        /// <remarks/>
        radioFolder,
        
        /// <remarks/>
        check,
        
        /// <remarks/>
        checkHideChildren,
        
        /// <remarks/>
        checkOffOnly,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute("refreshMode", Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public enum refreshModeEnumType {
        
        /// <remarks/>
        onChange,
        
        /// <remarks/>
        onInterval,
        
        /// <remarks/>
        onExpire,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute("shape", Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public enum shapeEnumType {
        
        /// <remarks/>
        rectangle,
        
        /// <remarks/>
        cylinder,
        
        /// <remarks/>
        sphere,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute("state", Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public enum itemIconStateEnumType {
        
        /// <remarks/>
        open,
        
        /// <remarks/>
        closed,
        
        /// <remarks/>
        error,
        
        /// <remarks/>
        fetching0,
        
        /// <remarks/>
        fetching1,
        
        /// <remarks/>
        fetching2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute("viewRefreshMode", Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public enum viewRefreshModeEnumType {
        
        /// <remarks/>
        never,
        
        /// <remarks/>
        onRequest,
        
        /// <remarks/>
        onStop,
        
        /// <remarks/>
        onRegion,
    }
}
