//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Math.Tools.TrackReaders.Kml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/kml/2.2", IsNullable=false)]
    public partial class kml {
        
        private kmlDocument documentField;
        
        /// <remarks/>
        public kmlDocument Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocument {
        
        private string nameField;
        
        private sbyte openField;
        
        private string descriptionField;
        
        private kmlDocumentStyle[] styleField;
        
        private kmlDocumentFolder[] folderField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public sbyte open {
            get {
                return this.openField;
            }
            set {
                this.openField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Style")]
        public kmlDocumentStyle[] Style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folder")]
        public kmlDocumentFolder[] Folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentStyle {
        
        private kmlDocumentStyleIconStyle iconStyleField;
        
        private kmlDocumentStyleLineStyle lineStyleField;
        
        private kmlDocumentStylePolyStyle polyStyleField;
        
        private kmlDocumentStyleBalloonStyle balloonStyleField;
        
        private string idField;
        
        /// <remarks/>
        public kmlDocumentStyleIconStyle IconStyle {
            get {
                return this.iconStyleField;
            }
            set {
                this.iconStyleField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentStyleLineStyle LineStyle {
            get {
                return this.lineStyleField;
            }
            set {
                this.lineStyleField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentStylePolyStyle PolyStyle {
            get {
                return this.polyStyleField;
            }
            set {
                this.polyStyleField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentStyleBalloonStyle BalloonStyle {
            get {
                return this.balloonStyleField;
            }
            set {
                this.balloonStyleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentStyleIconStyle {
        
        private kmlDocumentStyleIconStyleIcon iconField;
        
        /// <remarks/>
        public kmlDocumentStyleIconStyleIcon Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentStyleIconStyleIcon {
        
        private string hrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentStyleLineStyle {
        
        private string colorField;
        
        private float widthField;
        
        private bool widthFieldSpecified;
        
        /// <remarks/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public float width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool widthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentStylePolyStyle {
        
        private string colorField;
        
        /// <remarks/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentStyleBalloonStyle {
        
        private string textField;
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolder {
        
        private string nameField;
        
        private sbyte visibilityField;
        
        private bool visibilityFieldSpecified;
        
        private string descriptionField;
        
        private kmlDocumentFolderLookAt lookAtField;
        
        private string styleUrlField;
        
        private kmlDocumentFolderDocument documentField;
        
        private kmlDocumentFolderPlacemark[] placemarkField;
        
        private kmlDocumentFolderGroundOverlay groundOverlayField;
        
        private kmlDocumentFolderScreenOverlay[] screenOverlayField;
        
        private kmlDocumentFolderFolder[] folderField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public sbyte visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool visibilitySpecified {
            get {
                return this.visibilityFieldSpecified;
            }
            set {
                this.visibilityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderLookAt LookAt {
            get {
                return this.lookAtField;
            }
            set {
                this.lookAtField = value;
            }
        }
        
        /// <remarks/>
        public string styleUrl {
            get {
                return this.styleUrlField;
            }
            set {
                this.styleUrlField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderDocument Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Placemark")]
        public kmlDocumentFolderPlacemark[] Placemark {
            get {
                return this.placemarkField;
            }
            set {
                this.placemarkField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderGroundOverlay GroundOverlay {
            get {
                return this.groundOverlayField;
            }
            set {
                this.groundOverlayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScreenOverlay")]
        public kmlDocumentFolderScreenOverlay[] ScreenOverlay {
            get {
                return this.screenOverlayField;
            }
            set {
                this.screenOverlayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folder")]
        public kmlDocumentFolderFolder[] Folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderLookAt {
        
        private float longitudeField;
        
        private float latitudeField;
        
        private sbyte altitudeField;
        
        private float headingField;
        
        private float tiltField;
        
        private float rangeField;
        
        /// <remarks/>
        public float longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public float latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public sbyte altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
            }
        }
        
        /// <remarks/>
        public float heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
            }
        }
        
        /// <remarks/>
        public float tilt {
            get {
                return this.tiltField;
            }
            set {
                this.tiltField = value;
            }
        }
        
        /// <remarks/>
        public float range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderDocument {
        
        private string nameField;
        
        private sbyte visibilityField;
        
        private string descriptionField;
        
        private kmlDocumentFolderDocumentLookAt lookAtField;
        
        private kmlDocumentFolderDocumentStyle[] styleField;
        
        private kmlDocumentFolderDocumentStyleMap styleMapField;
        
        private kmlDocumentFolderDocumentPlacemark placemarkField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public sbyte visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderDocumentLookAt LookAt {
            get {
                return this.lookAtField;
            }
            set {
                this.lookAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Style")]
        public kmlDocumentFolderDocumentStyle[] Style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderDocumentStyleMap StyleMap {
            get {
                return this.styleMapField;
            }
            set {
                this.styleMapField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderDocumentPlacemark Placemark {
            get {
                return this.placemarkField;
            }
            set {
                this.placemarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderDocumentLookAt {
        
        private float longitudeField;
        
        private float latitudeField;
        
        private sbyte altitudeField;
        
        private sbyte headingField;
        
        private sbyte tiltField;
        
        private float rangeField;
        
        /// <remarks/>
        public float longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public float latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public sbyte altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
            }
        }
        
        /// <remarks/>
        public sbyte heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
            }
        }
        
        /// <remarks/>
        public sbyte tilt {
            get {
                return this.tiltField;
            }
            set {
                this.tiltField = value;
            }
        }
        
        /// <remarks/>
        public float range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderDocumentStyle {
        
        private kmlDocumentFolderDocumentStyleIconStyle iconStyleField;
        
        private string idField;
        
        /// <remarks/>
        public kmlDocumentFolderDocumentStyleIconStyle IconStyle {
            get {
                return this.iconStyleField;
            }
            set {
                this.iconStyleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderDocumentStyleIconStyle {
        
        private kmlDocumentFolderDocumentStyleIconStyleIcon iconField;
        
        /// <remarks/>
        public kmlDocumentFolderDocumentStyleIconStyleIcon Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderDocumentStyleIconStyleIcon {
        
        private string hrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderDocumentStyleMap {
        
        private kmlDocumentFolderDocumentStyleMapPair[] pairField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Pair")]
        public kmlDocumentFolderDocumentStyleMapPair[] Pair {
            get {
                return this.pairField;
            }
            set {
                this.pairField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderDocumentStyleMapPair {
        
        private string keyField;
        
        private string styleUrlField;
        
        /// <remarks/>
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string styleUrl {
            get {
                return this.styleUrlField;
            }
            set {
                this.styleUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderDocumentPlacemark {
        
        private string nameField;
        
        private sbyte visibilityField;
        
        private string styleUrlField;
        
        private kmlDocumentFolderDocumentPlacemarkPoint pointField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public sbyte visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        public string styleUrl {
            get {
                return this.styleUrlField;
            }
            set {
                this.styleUrlField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderDocumentPlacemarkPoint Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderDocumentPlacemarkPoint {
        
        private string coordinatesField;
        
        /// <remarks/>
        public string coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderPlacemark {
        
        private string nameField;
        
        private sbyte visibilityField;
        
        private bool visibilityFieldSpecified;
        
        private string descriptionField;
        
        private kmlDocumentFolderPlacemarkLookAt lookAtField;
        
        private string styleUrlField;
        
        private kmlDocumentFolderPlacemarkPoint pointField;
        
        private kmlDocumentFolderPlacemarkLineString lineStringField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public sbyte visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool visibilitySpecified {
            get {
                return this.visibilityFieldSpecified;
            }
            set {
                this.visibilityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderPlacemarkLookAt LookAt {
            get {
                return this.lookAtField;
            }
            set {
                this.lookAtField = value;
            }
        }
        
        /// <remarks/>
        public string styleUrl {
            get {
                return this.styleUrlField;
            }
            set {
                this.styleUrlField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderPlacemarkPoint Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderPlacemarkLineString LineString {
            get {
                return this.lineStringField;
            }
            set {
                this.lineStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderPlacemarkLookAt {
        
        private float longitudeField;
        
        private float latitudeField;
        
        private sbyte altitudeField;
        
        private float headingField;
        
        private float tiltField;
        
        private float rangeField;
        
        /// <remarks/>
        public float longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public float latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public sbyte altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
            }
        }
        
        /// <remarks/>
        public float heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
            }
        }
        
        /// <remarks/>
        public float tilt {
            get {
                return this.tiltField;
            }
            set {
                this.tiltField = value;
            }
        }
        
        /// <remarks/>
        public float range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderPlacemarkPoint {
        
        private sbyte extrudeField;
        
        private bool extrudeFieldSpecified;
        
        private string altitudeModeField;
        
        private string coordinatesField;
        
        /// <remarks/>
        public sbyte extrude {
            get {
                return this.extrudeField;
            }
            set {
                this.extrudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool extrudeSpecified {
            get {
                return this.extrudeFieldSpecified;
            }
            set {
                this.extrudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string altitudeMode {
            get {
                return this.altitudeModeField;
            }
            set {
                this.altitudeModeField = value;
            }
        }
        
        /// <remarks/>
        public string coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderPlacemarkLineString {
        
        private sbyte extrudeField;
        
        private bool extrudeFieldSpecified;
        
        private sbyte tessellateField;
        
        private string altitudeModeField;
        
        private string coordinatesField;
        
        /// <remarks/>
        public sbyte extrude {
            get {
                return this.extrudeField;
            }
            set {
                this.extrudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool extrudeSpecified {
            get {
                return this.extrudeFieldSpecified;
            }
            set {
                this.extrudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public sbyte tessellate {
            get {
                return this.tessellateField;
            }
            set {
                this.tessellateField = value;
            }
        }
        
        /// <remarks/>
        public string altitudeMode {
            get {
                return this.altitudeModeField;
            }
            set {
                this.altitudeModeField = value;
            }
        }
        
        /// <remarks/>
        public string coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderGroundOverlay {
        
        private string nameField;
        
        private sbyte visibilityField;
        
        private string descriptionField;
        
        private kmlDocumentFolderGroundOverlayLookAt lookAtField;
        
        private kmlDocumentFolderGroundOverlayIcon iconField;
        
        private kmlDocumentFolderGroundOverlayLatLonBox latLonBoxField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public sbyte visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderGroundOverlayLookAt LookAt {
            get {
                return this.lookAtField;
            }
            set {
                this.lookAtField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderGroundOverlayIcon Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderGroundOverlayLatLonBox LatLonBox {
            get {
                return this.latLonBoxField;
            }
            set {
                this.latLonBoxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderGroundOverlayLookAt {
        
        private float longitudeField;
        
        private float latitudeField;
        
        private sbyte altitudeField;
        
        private float headingField;
        
        private float tiltField;
        
        private float rangeField;
        
        /// <remarks/>
        public float longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public float latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public sbyte altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
            }
        }
        
        /// <remarks/>
        public float heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
            }
        }
        
        /// <remarks/>
        public float tilt {
            get {
                return this.tiltField;
            }
            set {
                this.tiltField = value;
            }
        }
        
        /// <remarks/>
        public float range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderGroundOverlayIcon {
        
        private string hrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderGroundOverlayLatLonBox {
        
        private float northField;
        
        private float southField;
        
        private float eastField;
        
        private float westField;
        
        private float rotationField;
        
        /// <remarks/>
        public float north {
            get {
                return this.northField;
            }
            set {
                this.northField = value;
            }
        }
        
        /// <remarks/>
        public float south {
            get {
                return this.southField;
            }
            set {
                this.southField = value;
            }
        }
        
        /// <remarks/>
        public float east {
            get {
                return this.eastField;
            }
            set {
                this.eastField = value;
            }
        }
        
        /// <remarks/>
        public float west {
            get {
                return this.westField;
            }
            set {
                this.westField = value;
            }
        }
        
        /// <remarks/>
        public float rotation {
            get {
                return this.rotationField;
            }
            set {
                this.rotationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderScreenOverlay {
        
        private string nameField;
        
        private sbyte visibilityField;
        
        private string descriptionField;
        
        private kmlDocumentFolderScreenOverlayIcon iconField;
        
        private kmlDocumentFolderScreenOverlayOverlayXY overlayXYField;
        
        private kmlDocumentFolderScreenOverlayScreenXY screenXYField;
        
        private kmlDocumentFolderScreenOverlayRotationXY rotationXYField;
        
        private kmlDocumentFolderScreenOverlaySize sizeField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public sbyte visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderScreenOverlayIcon Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderScreenOverlayOverlayXY overlayXY {
            get {
                return this.overlayXYField;
            }
            set {
                this.overlayXYField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderScreenOverlayScreenXY screenXY {
            get {
                return this.screenXYField;
            }
            set {
                this.screenXYField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderScreenOverlayRotationXY rotationXY {
            get {
                return this.rotationXYField;
            }
            set {
                this.rotationXYField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderScreenOverlaySize size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderScreenOverlayIcon {
        
        private string hrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderScreenOverlayOverlayXY {
        
        private float xField;
        
        private bool xFieldSpecified;
        
        private float yField;
        
        private bool yFieldSpecified;
        
        private string xunitsField;
        
        private string yunitsField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xSpecified {
            get {
                return this.xFieldSpecified;
            }
            set {
                this.xFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ySpecified {
            get {
                return this.yFieldSpecified;
            }
            set {
                this.yFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string xunits {
            get {
                return this.xunitsField;
            }
            set {
                this.xunitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string yunits {
            get {
                return this.yunitsField;
            }
            set {
                this.yunitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderScreenOverlayScreenXY {
        
        private float xField;
        
        private bool xFieldSpecified;
        
        private float yField;
        
        private bool yFieldSpecified;
        
        private string xunitsField;
        
        private string yunitsField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xSpecified {
            get {
                return this.xFieldSpecified;
            }
            set {
                this.xFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ySpecified {
            get {
                return this.yFieldSpecified;
            }
            set {
                this.yFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string xunits {
            get {
                return this.xunitsField;
            }
            set {
                this.xunitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string yunits {
            get {
                return this.yunitsField;
            }
            set {
                this.yunitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderScreenOverlayRotationXY {
        
        private float xField;
        
        private bool xFieldSpecified;
        
        private float yField;
        
        private bool yFieldSpecified;
        
        private string xunitsField;
        
        private string yunitsField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xSpecified {
            get {
                return this.xFieldSpecified;
            }
            set {
                this.xFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ySpecified {
            get {
                return this.yFieldSpecified;
            }
            set {
                this.yFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string xunits {
            get {
                return this.xunitsField;
            }
            set {
                this.xunitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string yunits {
            get {
                return this.yunitsField;
            }
            set {
                this.yunitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderScreenOverlaySize {
        
        private sbyte xField;
        
        private bool xFieldSpecified;
        
        private float yField;
        
        private bool yFieldSpecified;
        
        private string xunitsField;
        
        private string yunitsField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xSpecified {
            get {
                return this.xFieldSpecified;
            }
            set {
                this.xFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ySpecified {
            get {
                return this.yFieldSpecified;
            }
            set {
                this.yFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string xunits {
            get {
                return this.xunitsField;
            }
            set {
                this.xunitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string yunits {
            get {
                return this.yunitsField;
            }
            set {
                this.yunitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderFolder {
        
        private string nameField;
        
        private sbyte visibilityField;
        
        private bool visibilityFieldSpecified;
        
        private string descriptionField;
        
        private kmlDocumentFolderFolderLookAt lookAtField;
        
        private kmlDocumentFolderFolderPlacemark[] placemarkField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public sbyte visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool visibilitySpecified {
            get {
                return this.visibilityFieldSpecified;
            }
            set {
                this.visibilityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderFolderLookAt LookAt {
            get {
                return this.lookAtField;
            }
            set {
                this.lookAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Placemark")]
        public kmlDocumentFolderFolderPlacemark[] Placemark {
            get {
                return this.placemarkField;
            }
            set {
                this.placemarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderFolderLookAt {
        
        private float longitudeField;
        
        private float latitudeField;
        
        private sbyte altitudeField;
        
        private float headingField;
        
        private float tiltField;
        
        private float rangeField;
        
        /// <remarks/>
        public float longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public float latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public sbyte altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
            }
        }
        
        /// <remarks/>
        public float heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
            }
        }
        
        /// <remarks/>
        public float tilt {
            get {
                return this.tiltField;
            }
            set {
                this.tiltField = value;
            }
        }
        
        /// <remarks/>
        public float range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderFolderPlacemark {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LookAt", typeof(kmlDocumentFolderFolderPlacemarkLookAt))]
        [System.Xml.Serialization.XmlElementAttribute("Polygon", typeof(kmlDocumentFolderFolderPlacemarkPolygon))]
        [System.Xml.Serialization.XmlElementAttribute("name", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("styleUrl", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("visibility", typeof(sbyte))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderFolderPlacemarkLookAt {
        
        private float longitudeField;
        
        private float latitudeField;
        
        private sbyte altitudeField;
        
        private bool altitudeFieldSpecified;
        
        private float headingField;
        
        private float tiltField;
        
        private float rangeField;
        
        /// <remarks/>
        public float longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public float latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public sbyte altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool altitudeSpecified {
            get {
                return this.altitudeFieldSpecified;
            }
            set {
                this.altitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public float heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
            }
        }
        
        /// <remarks/>
        public float tilt {
            get {
                return this.tiltField;
            }
            set {
                this.tiltField = value;
            }
        }
        
        /// <remarks/>
        public float range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderFolderPlacemarkPolygon {
        
        private sbyte extrudeField;
        
        private bool extrudeFieldSpecified;
        
        private sbyte tessellateField;
        
        private bool tessellateFieldSpecified;
        
        private string altitudeModeField;
        
        private kmlDocumentFolderFolderPlacemarkPolygonOuterBoundaryIs outerBoundaryIsField;
        
        private kmlDocumentFolderFolderPlacemarkPolygonInnerBoundaryIs innerBoundaryIsField;
        
        /// <remarks/>
        public sbyte extrude {
            get {
                return this.extrudeField;
            }
            set {
                this.extrudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool extrudeSpecified {
            get {
                return this.extrudeFieldSpecified;
            }
            set {
                this.extrudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public sbyte tessellate {
            get {
                return this.tessellateField;
            }
            set {
                this.tessellateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tessellateSpecified {
            get {
                return this.tessellateFieldSpecified;
            }
            set {
                this.tessellateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string altitudeMode {
            get {
                return this.altitudeModeField;
            }
            set {
                this.altitudeModeField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderFolderPlacemarkPolygonOuterBoundaryIs outerBoundaryIs {
            get {
                return this.outerBoundaryIsField;
            }
            set {
                this.outerBoundaryIsField = value;
            }
        }
        
        /// <remarks/>
        public kmlDocumentFolderFolderPlacemarkPolygonInnerBoundaryIs innerBoundaryIs {
            get {
                return this.innerBoundaryIsField;
            }
            set {
                this.innerBoundaryIsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderFolderPlacemarkPolygonOuterBoundaryIs {
        
        private kmlDocumentFolderFolderPlacemarkPolygonOuterBoundaryIsLinearRing linearRingField;
        
        /// <remarks/>
        public kmlDocumentFolderFolderPlacemarkPolygonOuterBoundaryIsLinearRing LinearRing {
            get {
                return this.linearRingField;
            }
            set {
                this.linearRingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderFolderPlacemarkPolygonOuterBoundaryIsLinearRing {
        
        private string coordinatesField;
        
        /// <remarks/>
        public string coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderFolderPlacemarkPolygonInnerBoundaryIs {
        
        private kmlDocumentFolderFolderPlacemarkPolygonInnerBoundaryIsLinearRing linearRingField;
        
        /// <remarks/>
        public kmlDocumentFolderFolderPlacemarkPolygonInnerBoundaryIsLinearRing LinearRing {
            get {
                return this.linearRingField;
            }
            set {
                this.linearRingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/kml/2.2")]
    public partial class kmlDocumentFolderFolderPlacemarkPolygonInnerBoundaryIsLinearRing {
        
        private string coordinatesField;
        
        /// <remarks/>
        public string coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opengis.net/kml/2.2", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        LookAt,
        
        /// <remarks/>
        Polygon,
        
        /// <remarks/>
        name,
        
        /// <remarks/>
        styleUrl,
        
        /// <remarks/>
        visibility,
    }
}
